### ISSUE TITLE
Public server

### ISSUE THREAD

**Issue by patoux3** [hat3ph/docker-adguard-unbound#2]
Hi,

I would like to install it on a public server. When I am on the configuration page, there are only two IPs available, either 127.0.0.1 or container IP. How to get public server ip. Thanks

**Comment by hat3ph** [comment]
Just choose the container IP or listen to all interface. Check out my video on using the docker-adguard-unbound on Oracle Cloud.

https://youtu.be/Tv2oyBHqzOo
