### ISSUE TITLE
Add docker Dockerfile

### ISSUE THREAD

**Issue by plant7403** [hat3ph/docker-adguard-unbound#4]
The last image you pushed to docker-hub is around 1 year old
Consider adding the Dockerfiles to the repo, so people can build their own images

**Comment by hat3ph** [comment]
I have update the docker image, https://github.com/hat3ph/adguard-unbound, pls try the latest docker-compose.yml.

**Comment by hat3ph** [comment]
@xxxcrow, does the new docker image working?

**Comment by plant7403** [comment]
@hat3ph at the moment setting up a lot of stuff, got stuck with the default AGH home
But can try later

**Comment by plant7403** [comment]
@hat3ph I'm migrating my server, so already deployed the official image
When will have time I will try to upgrade to your image
Just add the link to the readme, or the dockerfile to the repo
Thanks for your work 🫡

**Comment by hat3ph** [comment]
@xxxcrow, check out new adguard-unbound v0.107.30 docker image.
